sonar.projectKey=Litzchill
sonar.host.url=http://localhost:9000
sonar.token=sqp_5171d375859c9fe3fa6f90a030ab4e2ec43ebd91
sonar.sources=functions
sonar.exclusions=**/node_modules/**, **/functions/tests/**, **/*.test.ts, **/*.spec.ts
sonar.language=ts
sonar.sourceEncoding=UTF-8
