sonar.projectKey=Litzchill-TestCases
sonar.host.url=http://localhost:9000
sonar.login=sqp_b14d30139f56cff75f9cb6571423c5156e31482b
sonar.sources=functions
sonar.exclusions=**/node_modules/**, **/functions/tests/**, **/*.test.ts, **/*.spec.ts
sonar.language=ts
sonar.sourceEncoding=UTF-8
